import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"
import { getServerSession } from "next-auth"
import SesstionProvider from "@/context/SessionProvider"
import { options } from "./api/auth/[...nextauth]/options"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(options)
  return (
    <SesstionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SesstionProvider>
  )
}
