import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { getServerSession } from "next-auth";
import SesstionProvider from "@/context/SessionProvider";
import SnackbarProvider from "@/context/NotistackProvider";
import { options } from "./api/auth/[...nextauth]/options";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  return (
    <SesstionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Suspense fallback={<Loading />}>
            <SnackbarProvider>{children}</SnackbarProvider>
          </Suspense>
        </body>
      </html>
    </SesstionProvider>
  );
}
