import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AdminNav from "@/components/AdminNav";
import AdminMenu from "@/components/AdminMenu";
import "./globals.css";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> <Box>
          <AdminNav/>
          <Box sx={{ display: "flex" }}>
            <AdminMenu />
            <Box sx={{ flex: 1, margin: "10px 30px" }}>
              {children}
            </Box>
          </Box>
        </Box></body>
    </html>
  );
}
